chore(authentifier): Add initial setup (#10)

diff --git a/common/git-hooks/commit-msg b/common/git-hooks/commit-msg
--- a/common/git-hooks/commit-msg
+++ b/common/git-hooks/commit-msg
@@ -1,6 +1,6 @@
 #!/bin/sh
-if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
-    echo "aborted: Your commit message doesn't respect conventional commit convention" >&2
+if ! head -1 "$1" | grep -qE "^(<type>feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)\((<scope>global|signifier|authentifier)\)?: .{1,}$"; then
+    echo "aborted: Your commit message doesn't respect conventional commit syntax" >&2
     exit 1
 fi
 if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
